#version 430 core

layout(shared, binding = 1) buffer voxels
{
	uvec4[] posses;
};

layout(binding = 2, offset = 0) uniform atomic_uint posCount;

layout(local_size_x = MCM_VOX_COUNT, local_size_y = 1, local_size_z = MCM_VOX_COUNT) in;

#include vox_helper.inc

void main()
{
	int counted = count_visible_verts(gl_GlobalInvocationID);
	for (int i = 0; i < counted; i++)
	{
		atomicCounterIncrement(posCount);
	}
}
